name: build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: mpv-android-2025-12-27

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive # Required for mpv

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: temurin

      - name: Fix permissions
        run: chmod -R +x buildscripts

      - name: Export env vars
        run: bash buildscripts/include/ci.sh export >> $GITHUB_ENV

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf pkgconf libtool ninja-build python3-pip gperf
          pip3 install meson

      - name: Download build deps
        run: bash buildscripts/include/ci.sh install
        env:
          CACHE_MODE: "folder"
          CACHE_FOLDER: "${{ github.workspace }}/mpv-android-2025-12-27/gh-cache"

      - name: Build APK
        run: bash buildscripts/include/ci.sh build

      - name: Verify APK Location
        # This will print the exact location of the APK in your logs
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: mpv-build-result
          # This tells GitHub to grab any APK it finds inside your folder
          path: mpv-android-2025-12-27/**/*.apk
          if-no-files-found: error

          
